version: "3"

services:
  # project name?
  # 大文字はダメ
  goandmysql:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - PORT
    container_name: GoAndMySQL
    stdin_open: true
    tty: true
    volumes: 
      - .:/go/src/app
    ports: 
      - ${PORT}:${PORT}